export const sculptureList = [
{
    id:1,
    name:"ระบบสมาร์ทฟาร์ม",
    author:"Mikari",
    description:"โครงานเกี่ยวกับการใช้งานระบบ I0T สำหรับการตรวจสอบสภาพเเวดล้อมอัตโนมัติ",
    url:"/images/proj1.png",
    reference: "https://smartfarmpro.info/?gad_source=1&gclid=CjwKCAjwzIK1BhAuEiwAHQmU3qlsA4l_FllnnnX20MkahXX0116VDr58SLP2Vh2HLxypk_yKbYHJPhoCq6cQAvD_BwE",
},
{ 
    id:2,
    name:"Steam",
    author:"eiei",
    description:"โปรแกรมซื้อเกมออนไลน์",
    url:"/images/proj2.png",
    reference: "https://store.steampowered.com/?l=thai",
},
{ 
    id:3,
    name:"RichmanShop",
    author:"Richman",
    description:"เว็บเติมเกมออนไลน์",
    url:"/images/proj3.png",
    reference: "https://richmanshop.com/home?gad_source=1&gclid=CjwKCAjwzIK1BhAuEiwAHQmU3lnvdZBjnAphLs9qXPD5X_tebXWjRjd595JMPYk0CMOJU7-9ffjkjBoC0TEQAvD_BwE",
},
{
    id:4,
    name:"Honkai star rail",
    author:"Hoyoverse",
    description:"เกมออนไลน์",
    url:"/images/proj4.png",
    reference: "https://hsr.hoyoverse.com/ua2?lp=sr03&utm_source=SEA_google_SEA_search_UA2_Brand&hoyotrace_channel=ga_channel&gad_source=1&gclid=CjwKCAjwzIK1BhAuEiwAHQmU3uVhirobUgkV3JA8eief5zZ6HYjCVmphoFr_NY_PnjAkgtqCjGSYrRoCGAMQAvD_BwE",
},
{
    id:5,
    name:"Genshin impact",
    author:"Hoyoverse",
    description:"เกมออนไลน์",
    url:"/images/proj5.png",
    reference: "https://genshin.hoyoverse.com/th/",
},
{
    id:6,
    name:"Point Bank",
    author:"Zepetto",
    description:"เกมออนไลน์",
    url:"/images/proj6.png",
    reference: "https://pointblank.zepetto.com/th/game/download",
},
];